
class Modifier {
  static isModifier (mod) {
    return [
      // names
      'Oda', 'Salim', 'Dimo', 'Catalan', 'Rut', 'Luli', 'Shu', 'Chow',
      'Wang', 'Jia', 'Xia', 'Chen', 'Akemi', 'Lin', 'Lee', 'Nikola',
      'Josef', 'Freja', 'Daan', 'Lotte', 'Bram', 'Zoe', 'Isla', 'Evie',
      'Jack', 'Rose', 'Clara', 'Emma', 'Mason', 'Alice', 'Nancy',
      'Lily', 'Harry', 'Eka', 'Jai', 'Ajit', 'Oran', 'Linda', 'Amy',
      'Mary', 'John', 'Mike', 'Aada', 'Emile', 'Olivia', 'Logan',
      'Felix', 'Bette', 'Iva', 'Zola', 'Axel', 'Theo', 'Lukas',
      'Hanna', 'Lina', 'Jonas', 'Tim', 'Neo', 'Rami', 'Puja', 'Kabir',
      'Mate', 'Intan', 'Bria', 'Mia', 'Pietro', 'Hina', 'Airi', 'Fumi',
      'Akira', 'Nari', 'Aqil', 'Marte', 'Erik', 'Julia', 'Jan',
      'Marcia', 'Ligia', 'Yara', 'Dinis', 'Leonor', 'Doru', 'Olga',
      'Marina', 'Peter', 'Beda', 'Vid', 'Juana', 'Silvia', 'Teresa',
      'Jose', 'Camila', 'Sofia', 'Luna', 'Diego', 'Molly', 'Hugo',
      'Sai', 'Ukrit', 'Omer', 'Chi',
      // langs
      'ar-eg', 'ar-sa', 'bg-bg', 'zh-cn', 'zh-hk', 'zh-tw', 'hr-hr',
      'cs-cz', 'da-dk', 'nl-be', 'nl-nl', 'en-au', 'en-ca', 'en-gb',
      'en-in', 'en-ie', 'en-us', 'fi-fi', 'fr-ca', 'fr-fr', 'fr-ch',
      'de-at', 'de-de', 'de-ch', 'el-gr', 'he-il', 'hi-in', 'hu-hu',
      'id-id', 'it-it', 'ja-jp', 'ko-kr', 'ms-my', 'nb-no', 'pl-pl',
      'pt-br', 'pt-pt', 'ro-ro', 'ru-ru', 'sk-sk', 'sl-si', 'es-mx',
      'es-es', 'sv-se', 'ta-in', 'th-th', 'tr-tr', 'vi-vn'
    ].includes(mod);
  }

  static get voiceTable () {
    return {
      Oda: 'ar-eg',
      Salim: 'ar-sa',
      Dimo: 'bg-bg',
      Catalan: 'bg-bg',
      Rut: 'bg-bg',
      Luli: 'zh-cn',
      Shu: 'zh-cn',
      Chow: 'zh-cn',
      Wang: 'zh-cn',
      Jia: 'zh-hk',
      Xia: 'zh-hk',
      Chen: 'zh-hk',
      Akemi: 'zh-tw',
      Lin: 'zh-tw',
      Lee: 'zh-tw',
      Nikola: 'hr-hr',
      Josef: 'cs-cz',
      Freja: 'da-dk',
      Daan: 'nl-be',
      Lotte: 'nl-nl',
      Bram: 'nl-nl',
      Zoe: 'en-au',
      Isla: 'en-au',
      Evie: 'en-au',
      Jack: 'en-au',
      Rose: 'en-ca',
      Clara: 'en-ca',
      Emma: 'en-ca',
      Mason: 'en-ca',
      Alice: 'en-gb',
      Nancy: 'en-gb',
      Lily: 'en-gb',
      Harry: 'en-gb',
      Eka: 'en-in',
      Jai: 'en-in',
      Ajit: 'en-in',
      Oran: 'en-ie',
      Linda: 'en-us',
      Amy: 'en-us',
      Mary: 'en-us',
      John: 'en-us',
      Mike: 'en-us',
      Aada: 'fi-fi',
      Emile: 'fr-ca',
      Olivia: 'fr-ca',
      Logan: 'fr-ca',
      Felix: 'fr-ca',
      Bette: 'fr-fr',
      Iva: 'fr-fr',
      Zola: 'fr-fr',
      Axel: 'fr-fr',
      Theo: 'fr-ch',
      Lukas: 'de-at',
      Hanna: 'de-de',
      Lina: 'de-de',
      Jonas: 'de-de',
      Tim: 'de-ch',
      Neo: 'el-gr',
      Rami: 'he-il',
      Puja: 'hi-in',
      Kabir: 'hi-in',
      Mate: 'hu-hu',
      Intan: 'id-id',
      Bria: 'it-it',
      Mia: 'it-it',
      Pietro: 'it-it',
      Hina: 'ja-jp',
      Airi: 'ja-jp',
      Fumi: 'ja-jp',
      Akira: 'ja-jp',
      Nari: 'ko-kr',
      Aqil: 'ms-my',
      Marte: 'nb-no',
      Erik: 'nb-no',
      Julia: 'pl-pl',
      Jan: 'pl-pl',
      Marcia: 'pt-br',
      Ligia: 'pt-br',
      Yara: 'pt-br',
      Dinis: 'pt-br',
      Leonor: 'pt-pt',
      Doru: 'ro-ro',
      Olga: 'ru-ru',
      Marina: 'ru-ru',
      Peter: 'ru-ru',
      Beda: 'sk-sk',
      Vid: 'sl-si',
      Juana: 'es-mx',
      Silvia: 'es-mx',
      Teresa: 'es-mx',
      Jose: 'es-mx',
      Camila: 'es-es',
      Sofia: 'es-es',
      Luna: 'es-es',
      Diego: 'es-es',
      Molly: 'sv-se',
      Hugo: 'sv-se',
      Sai: 'ta-in',
      Ukrit: 'th-th',
      Omer: 'tr-tr',
      Chi: 'vi-vn'
    };
  }
}

module.exports = Modifier;
